require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0

RSpec/ExampleLength:
  Max: 18

RSpec/NestedGroups:
  Max: 4

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
