inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
